/* EXiLED wiki — a character who notices their own page.
   generated by wiki/build.mjs */
(function(){
  var el = document.getElementById('cameo');
  if(!el) return;
  var LINES = {
    ghostie: {
      hello:  ["oh that's me btw!", "hey! that's me!", "you found my page. hi.", "this is my good side.",
               "oh no. it's me. on the internet.", "don't believe everything in here.", "they got my teardrop right at least."],
      sulk:   ["...still sulking. but yes. that's me.", "i'm not talking to you. (that's me though.)"],
      poke:   ["yes, still me.", "i didn't write this, for the record.", "the picture's flattering. i'll allow it.",
               "a hand's span. HUH. rude.", "i'm right here, you know.", "read the trivia. the trivia's the best part."],
      identity:  ["...we don't talk about that part.", "skip this bit. please."],
      behaviour: ["this section is slander.", "the poking part is NOT a challenge."]
    }
  };
  var who = el.getAttribute('data-who'), L = LINES[who];
  if(!L) return;
  var say = el.querySelector('.say'), frames = {};
  ['idle', 'blink', 'talk'].forEach(function(f){ frames[f] = el.querySelector('.f-' + f); });
  function frame(k){ for(var f in frames) if(frames[f]) frames[f].classList.toggle('show', f === k); }
  function pick(a){ return a[Math.floor(Math.random() * a.length)]; }
  var talking = false, sayId = 0, flap = 0;
  function speak(text, ms){
    var id = ++sayId; clearInterval(flap);
    talking = true; say.textContent = text; say.classList.add('on');
    var n = 0; flap = setInterval(function(){ frame(n++ % 2 ? 'idle' : 'talk'); }, 130);
    setTimeout(function(){ if(id !== sayId) return; clearInterval(flap); frame('idle'); talking = false; say.classList.remove('on'); }, ms || 2800);
  }
  (function blink(){
    if(!talking){ frame('blink'); setTimeout(function(){ if(!talking) frame('idle'); }, 120); }
    setTimeout(blink, 2400 + Math.random() * 3600);
  })();
  /* a sulk from the main page follows them here */
  var sulking = false;
  try{ sulking = (+localStorage.getItem('exiled.ghostiePoof') || 0) > Date.now(); }catch(e){}
  setTimeout(function(){
    el.classList.add('live');
    setTimeout(function(){ speak(pick(sulking && L.sulk ? L.sulk : L.hello), 3200); }, 900);
  }, 1200);
  /* the main page gets to say something about this later */
  try{ if(!localStorage.getItem('exiled.readFile')) localStorage.setItem('exiled.readFile', '1'); }catch(e){}
  var last = 0;
  el.addEventListener('click', function(){
    if(Date.now() - last < 900) return;
    last = Date.now(); speak(pick(L.poke), 2600);
  });
  /* a section they have opinions about, once each */
  if('IntersectionObserver' in window){
    var said = {};
    var io = new IntersectionObserver(function(es){
      es.forEach(function(en){
        var k = en.target.getAttribute('data-k');
        if(!en.isIntersecting || said[k]) return;
        said[k] = 1; speak(pick(L[k]), 3000);
      });
    }, { rootMargin: '0px 0px -40% 0px' });
    Array.prototype.forEach.call(document.querySelectorAll('article h2'), function(h){
      var k = h.textContent.trim().toLowerCase();
      if(L[k]){ h.setAttribute('data-k', k); io.observe(h); }
    });
  }
})();
