/* EXiLED wiki — lives inside the main page. generated by wiki/build.mjs */
(function(){
  var framed;
  try { framed = window.top !== window; } catch(e){ return; }
  if(!framed){
    location.replace('/#/' + location.pathname.replace(/^\/+/, '') + location.hash);
    return;
  }
  var shell = null;
  try { shell = window.top.exiledShell; } catch(e){}
  if(!shell) return;
  document.addEventListener('click', function(e){
    if(e.defaultPrevented || e.button || e.metaKey || e.ctrlKey || e.shiftKey || e.altKey) return;
    var a = e.target && e.target.closest && e.target.closest('a[href]');
    if(!a) return;
    var u;
    try { u = new URL(a.getAttribute('href'), location.href); } catch(err){ return; }
    if(u.origin !== location.origin){ e.preventDefault(); window.open(u.href, '_blank', 'noopener'); return; }
    var p = u.pathname.replace(/^\/+/, '');
    if(p === '' || p === 'index.html'){ e.preventDefault(); shell.close(); return; }
    if(p === 'databytes.html'){ e.preventDefault(); shell.bytes(); }
  });
})();
