/* EXiLED wiki — opens a sealed entry for a browser that holds the key.
   generated by wiki/build.mjs */
(function(){
  var root = document.documentElement, slug = document.body.getAttribute('data-sealed');
  var isIndex = !slug && document.body.getAttribute('data-wiki-index') !== null;
  function done(){ root.classList.remove('unsealing'); }
  setTimeout(done, 2500);
  var k = null; try{ k = localStorage.getItem('exiled.vault'); }catch(e){}
  var S = window.EXILED_SEAL, ent = slug && S && S.entries && S.entries[slug];
  if(!k || !S || !window.crypto || !crypto.subtle || (!ent && !isIndex)) return done();
  function bytes(s){ return Uint8Array.from(atob(s), function(c){ return c.charCodeAt(0); }); }
  var keyP = crypto.subtle.importKey('raw', bytes(k), 'AES-GCM', false, ['decrypt']);

  /* the index: a key that opens the check blob opens every sealed entry,
     so their rows stop saying SEALED */
  if(isIndex){
    keyP.then(function(key){ return crypto.subtle.decrypt({ name: 'AES-GCM', iv: bytes(S.check.iv) }, key, bytes(S.check.ct)); })
      .then(function(){
        [].forEach.call(document.querySelectorAll('a.entry.sealed'), function(a){
          a.classList.remove('sealed');
          var st = a.querySelector('.s'); if(st) st.textContent = 'RECOVERED';
        });
      }, function(){});
    return done();
  }

  keyP.then(function(key){
    return crypto.subtle.decrypt({ name: 'AES-GCM', iv: bytes(ent.iv) }, key, bytes(ent.ct)).then(function(buf){
      var t = document.createElement('template');
      t.innerHTML = new TextDecoder().decode(buf);
      document.querySelector('main').replaceWith(t.content);
      done();
      /* the portrait: fetched as ciphertext, opened here, shown as a blob */
      if(!document.querySelectorAll) return;
      [].forEach.call(document.querySelectorAll('img[data-seal-src]'), function(img){
        fetch(img.getAttribute('data-seal-src')).then(function(r){ return r.arrayBuffer(); }).then(function(ab){
          var all = new Uint8Array(ab);
          return crypto.subtle.decrypt({ name: 'AES-GCM', iv: all.slice(0, 12) }, key, all.slice(12));
        }).then(function(pt){
          img.src = URL.createObjectURL(new Blob([pt], { type: img.getAttribute('data-type') || 'image/jpeg' }));
        }, function(){});
      });
    });
  }).then(null, done);
})();
