/* EXiLED wiki — opens a sealed entry for a browser that holds the key.
   generated by wiki/build.mjs */
(function(){
  var root = document.documentElement, slug = document.body.getAttribute('data-sealed');
  function done(){ root.classList.remove('unsealing'); }
  setTimeout(done, 2500);
  var k = null; try{ k = localStorage.getItem('exiled.vault'); }catch(e){}
  var S = window.EXILED_SEAL, ent = S && S.entries && S.entries[slug];
  if(!k || !ent || !window.crypto || !crypto.subtle) return done();
  function bytes(s){ return Uint8Array.from(atob(s), function(c){ return c.charCodeAt(0); }); }
  crypto.subtle.importKey('raw', bytes(k), 'AES-GCM', false, ['decrypt'])
    .then(function(key){ return crypto.subtle.decrypt({ name: 'AES-GCM', iv: bytes(ent.iv) }, key, bytes(ent.ct)); })
    .then(function(buf){
      var t = document.createElement('template');
      t.innerHTML = new TextDecoder().decode(buf);
      document.querySelector('main').replaceWith(t.content);
      done();
    }, done);
})();
